---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx

- name: Create Drupal web root directory
  file:
    path: "{{ drupal_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Deploy Nginx virtual host config for Drupal
  template:
    src: drupal.conf.j2
    dest: /etc/nginx/sites-available/drupal.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Enable Drupal Nginx site
  file:
    src: /etc/nginx/sites-available/drupal.conf
    dest: /etc/nginx/sites-enabled/drupal.conf
    state: link
  notify: Restart Nginx

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

